sudo: required
language: bash
services: docker

# Skipping the Installation Step
install: true

script:
  - docker build -t android-build-box .

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push mathroule/docker-android-build-box;
    fi
